/* Generated from raphnet-n64-port-map-v1.json. */
/* OEM physical labels verified on retail Xbox; Hori layout equivalence owner stated. */
#ifndef RAPHNET_N64_PORT_MAP_V1_H
#define RAPHNET_N64_PORT_MAP_V1_H
enum RaphnetN64SDLButton {
    RAPHNET_N64_BUTTON_A = 0,
    RAPHNET_N64_BUTTON_B = 1,
    RAPHNET_N64_BUTTON_Z = 2,
    RAPHNET_N64_BUTTON_START = 3,
    RAPHNET_N64_BUTTON_L = 4,
    RAPHNET_N64_BUTTON_R = 5,
    RAPHNET_N64_BUTTON_C_UP = 6,
    RAPHNET_N64_BUTTON_C_DOWN = 7,
    RAPHNET_N64_BUTTON_C_LEFT = 8,
    RAPHNET_N64_BUTTON_C_RIGHT = 9,
    RAPHNET_N64_BUTTON_DPAD_UP = 10,
    RAPHNET_N64_BUTTON_DPAD_DOWN = 11,
    RAPHNET_N64_BUTTON_DPAD_LEFT = 12,
    RAPHNET_N64_BUTTON_DPAD_RIGHT = 13,
};
#define RAPHNET_N64_SDL_BUTTON_COUNT 16
#define RAPHNET_N64_AXIS_STICK_X 0
#define RAPHNET_N64_AXIS_STICK_Y 1
#define RAPHNET_N64_STICK_LEFT_NEGATIVE 1
#define RAPHNET_N64_STICK_UP_NEGATIVE 1
#endif
